### ISSUE TITLE
The homescreen request when you have multiple sync units?

### ISSUE THREAD

**Issue by HughAndersonNUS** [MattTW/BlinkMonitorProtocol#13]
Hi,
Thanks for your work on this, it has been very handy for me. I have a small issue...
If I have one sync unit in my mobile, and I do a homescreen URL, I get the homescreen info. However, if I add another system, I only get the second system. You can see the effect without needing a second sync unit. Just add another system...
Is there any way of getting the first system info, or both?
Cheers Hugh

**Comment by Xurn** [comment]
Not sure if you figured it out yet or not... but here's what I discovered:
https://rest._[region]_.immedia-semi.com/network/_[network-id]_/homescreen

Cheers!
