### ISSUE TITLE
Is this still working as of Thu, Oct 12, 2017?

### ISSUE THREAD

**Issue by dstrickler** [MattTW/BlinkMonitorProtocol#15]
I'm getting the authToken back, but I can't get a networks list with it {"message":"Unauthorized Access","code":101}, which seems to be the next logical step. 

I'd be happy to contribute to the docs (and maybe a library), but I need to get the basics working first.

TIA if I'm doing something noob.

Dave

**Comment by cbetta** [comment]
@dstrickler did you manage to resolve this? Getting the same error

**Comment by dstrickler** [comment]
@cbetta I did get past this point, but not much further. 

For getting a list of networks, I called the API as GET to "https://rest.prd2.immedia-semi.com/network", and passed in the HTTP header:
```
        "Host: $region_prefix" . ".immedia-semi.com",
        "TOKEN_AUTH:  $auth_token",
```
(pardon the PHP code). The $auth_token value was from when you logged in, the step before this one. The $region_prefix is different around the world, but I found the USA one to be "prd2" which you can see in as part of the URL above.

Using the above info, I was able to have their API list out the two "networks" (aka base stations) I have, but I was unable to use the network ID they listed to access any cameras for arm/disarm or any other function. I'm getting a "page not found" error. I'm clueless as to how to fix this.

I'm happy to share any tidbits I find, and please do the same.

Thanks,

**Comment by cbetta** [comment]
@dstrickler tnx for the details. I've given up for now but might pick it up again somewhere later this week.

**Comment by duangenquan** [comment]
@cbetta , [this repo](https://github.com/duangenquan/blink) contains some experiments recently on some blink xt camera. Hope this helps.

**Comment by cbetta** [comment]
Excellent, thanks @duangenquan
