### ISSUE TITLE
Unauthorized Access

### ISSUE THREAD

**Issue by kkaravouzis** [MattTW/BlinkMonitorProtocol#19]

**Comment by toddcurry** [comment]
I'll jump in here on this "thread" to add:
- I used the login Curl to get my auth token
- as fast as my chubby fingers can copy / paste, I grab the auth token from the response and...
- try submitting any other request that requires the auth token
- response is always:
{"message":"Unauthorized Access","code":101}

**Comment by geoffharden** [comment]
Did you ever find a fix for this? I'm seeing the same thing.

**Comment by toddcurry** [comment]
No - I gave up, I am sad to say...

**Comment by geoffharden** [comment]
Actually, I just figured it out. I re-read the notes in the login section and it mentions that there are different sub-domains by region. Then looking at the some of the other issues like [https://github.com/MattTW/BlinkMonitorProtocol/issues/20](url) shows that there is a https://rest-u001.immedia-semi.com, that u001 comes from the "dns" property in the regions call. So it looks like any call where you need to access your devices needs to come from https://[REGION SUB DOMAIN].immedia-semi.com, e.g. u001 for the US .
