### ISSUE TITLE
URL to register callback

### ISSUE THREAD

**Issue by rboy1** [MattTW/BlinkMonitorProtocol#2]
Also posted the question on zipsnet
Any idea what the URL would be to register a callback notification for alerts?

**Comment by MattTW** [comment]
I haven't seen any callback stuff in what I have looked at so far - the API seems to assume that clients will poll for status at regular intervals - which is what the mobile client does.   

The REST API isn't really meant to be public, yet - it feels pretty coupled to the mobile app.   A true public API is still on Blink's roadmap, I would expect things like callbacks at that point.

**Comment by rboy1** [comment]
Awesome thanks, somehow looking at the code I got the impression that it was registering a callback.
I think you're right because if I enable it remotely and I look at the mobile app it doesn't seem to register it until I refresh it.

**Comment by rboy1** [comment]
Do you know what it's looking at? I'm presuming references to unwatched videos and events or am I missing something?

**Comment by rboy1** [comment]
I see this while making all Blink API calls hence my suspicision

BlinkAPI.BlinkAPICallback()

**Comment by MattTW** [comment]
There could very well be callbacks in the client API.   When I traced the HTTP network behavior of the client,  I did not see anything that led me to believe there were callbacks being.   My network trace only focused on HTTP traffic and arming/disarming behavior.   Somebody else may know more and be able to chime in.
