### ISSUE TITLE
two cameras - same time - overwrites prior clip

### ISSUE THREAD

**Issue by nhhandyman** [MattTW/BlinkMonitorProtocol#22]
I have two cameras which are pointed in the same general direction.  If they both record motion at the same time, this downloader will create a file of the same name - last one wins - the other is lost.

I would suggest the file creation be changed to see if the proposed file already exists and if so - add a suffix to it.

**Comment by DCCoder90** [comment]
@nhhandyman  MattTW just merged a pull request that fixes this issue
