### ISSUE TITLE
latest update - ssl error

### ISSUE THREAD

**Issue by nhhandyman** [MattTW/BlinkMonitorProtocol#25]
this is from behind a firewall with proxies but the error I get after the changes to use the region in the url is below.  This is being run from a Linux Mint with python 2.7 from eclipse (project was cloned from github).

v7pUybmX33pXxELn_z7XJQ
https://rest-prod.immedia-semi.com/api/v2/videos/page/0
Traceback (most recent call last):
  File "/home/nhhandyman/git/BlinkMonitorProtocol/blinkVideoDownloader.py", line 34, in <module>
    res = requests.get(pageNumUrl, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 570, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'rest-prod.immedia-semi.com' doesn't match '*.prod.immedia-semi.com'

**Comment by DCCoder90** [comment]
It looks like the region that it is trying to connect to may be using an untrusted SSL certificate.  I will investigate this.  As a work around you could try changing 

`    res = requests.get(pageNumUrl, headers=headers)`

on line 34 to 

`    res = requests.get(pageNumUrl, headers=headers, verify=False)`

this will disable the certificate verification.

**Comment by nhhandyman** [comment]
Thanks

**Comment by rogerjbos** [comment]
I am current getting this error connection here in the US: 
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

**Comment by DCCoder90** [comment]
On line 41 replace

res = requests.get(pageNumUrl, headers=headers)

with

res = requests.get(pageNumUrl, headers=headers, verify=False)

this is due to not having the appropriate certificates installed on your computer.  The official Blink applications come bundled with them, but since this is an unofficial implementation we don't.

**Comment by rogerjbos** [comment]
Sorry, I think it was on my end.  I uninstalled pyOpenSSL using pip and re-installed it using conda and now I don't get the handshake error.
