### ISSUE TITLE
As of last night - downloader is missing many videos

### ISSUE THREAD

**Issue by nhhandyman** [MattTW/BlinkMonitorProtocol#30]
I can't pinpoint why - but there are several videos that are simply being skipped during the download.  

Its easy to notice this because the blink app still shows them as unseen.

Has anyone else noticed this behavior?

**Comment by mydarx** [comment]
maybe due to a change of the endpoints .... again, the blink guys changed there api - what a mess. The old endpoint delivers something but the new videos are not accessible there.
use "/api/v1/accounts/<account>/media/changed?since=..." which works. But also some fields have changed in the response. videos are under [media], camera:_id is now device_id etc.

**Comment by nhhandyman** [comment]
Thanks - I'll try that this evening.  They did release a new product (two way voice) and since they are the 'only' provider of the app - they can consider themselves owners of the api and free to do anything they want to it.

I am curious as to what tools are being used to capture the new api - I assume they are running on the phone where the app is running?

**Comment by mydarx** [comment]
> Thanks - I'll try that this evening. They did release a new product (two way voice) and since they are the 'only' provider of the app - they can consider themselves owners of the api and free to do anything they want to it.
> 
Sure, they are free in doing what they want. I just ask myself what the rationale is? It's just a switching back and forth between various endpoints, hardly any functional or feature progress, Maybe they want to make our lifes just a bit more exciting  :-) 

Regarding tools: with the new versions of android (as of Android N+) no chance anymore. the only way is SSL proxying on Android with a version prior to N (as long as the app runs there....)

**Comment by nhhandyman** [comment]
I think I misunderstood the change you suggested...

    pageNumUrl = 'https://rest-'+region+'.immedia-semi.com/api/v1/accounts/media/changed?since=2019-04-19T23:11:20+0000&page=' + str(pageNum)

results in a not-found result

**Comment by serge-v** [comment]
add accountID: /api/v1/accounts/{accountID}/media/changed

**Comment by nhhandyman** [comment]
Thanks to both of you!

    pageNumUrl = 'https://rest-'+region+'.immedia-semi.com/api/v1/accounts/'+accountID+'/media/changed?since=2019-04-19T23:11:20+0000&page=' + str(pageNum)

works.  
I didn't see the account ID called out directly in the login response so I got the Id using this:

network = res.json()["networks"]
accountID = list(network.keys())[0]

and with a few changes from "videos" to "media" and "camera_name" to "device_name" - the downloader is back working.

**Comment by BLINKCAMERASUCKS** [comment]
HELP. I noticed my download script stopped working and I was really using it to make this thing work. I tried really hard to make the updates listed here and I still get nothing. Any chance fronzbot or nhhandyman can post the updated script for less gifted community members? Thanks

**Comment by Zipsnet** [comment]
Try this

https://pastebin.com/raw/3r3GEEaL

**Comment by BLINKCAMERASUCKS** [comment]
Thanks Zipsnet. I really just needed to take the video download script Blink.PS1 and correct it as described above so that it would work with the new API. That that was like crazy.
