### ISSUE TITLE
Opening Downloaded Files

### ISSUE THREAD

**Issue by knlklabacka** [MattTW/BlinkMonitorProtocol#45]
Hello,  first I want to thank you for the great script.  The script works!  Second, I was wondering if you had any insight on why I cant open the downloaded mp4? I have used multiple players, VLC, Win Media player, and Win Movie app.  All three say the file is corrupt.  

Thank you!!

**Comment by cdeeran** [comment]
Hi, I have recently started using this library and I have not encountered this problem. My system is Win10 and my default media player is Movies & TV.

https://www.microsoft.com/en-us/p/movies-tv/9wzdncrfj3p2?activetab=pivot:overviewtab
