### ISSUE TITLE
ERROR: The request could not be satisfied

### ISSUE THREAD

**Issue by Nathan1258** [MattTW/BlinkMonitorProtocol#47]
When sending a HTTP `GET /api/v3/accounts/{AccountID}/homescreen`

**Comment by npcingham** [comment]
@Nathan1258 did you get this resolved? I'm seeing same error and therefore I think can't get accurate camera ids as they seem to be different to device ids as returned in video events response.

**Comment by Nathan1258** [comment]
I did not I'm afraid, I ended up trying to make my own python Wrapper/API for it that I have not yet finished. It's a shame because this repo seems like the only proper one out there. Let me know if you find a resolution, I'd appreciate it :)

> @Nathan1258 did you get this resolved? I'm seeing same error and therefore I think can't get accurate camera ids as they seem to be different to device ids as returned in video events response.

**Comment by MattTW** [comment]
Hmm, I just did a quick trace of the current Blink iOS client and the login and homescreen API's don't seem to have changed.  

Made a call to login then called homescreen using a standard REST client (Insomnia) and got expected responses.

Can you post the request and replies for your login and homescreen calls? - be sure to edit out anything personal in the calls...

**Comment by colinbendell** [comment]
I've encountered this when I've had a long running socket and Blink is doing a software update. closing the http socket and re-auth'ing cleared this issue.

**Comment by Nathan1258** [comment]
> I've encountered this when I've had a long running socket and Blink is doing a software update. closing the http socket and re-auth'ing cleared this issue.

I will try again and get back to you @MattTW with the request and replies.

**Comment by Nathan1258** [comment]
@MattTW  is the URL https://rest-prod.immedia-semi.com your own URL or blink's servers? I'm assuming you listened on a device when it was making calls to make the list of all requests going to Blink's servers?

**Comment by colinbendell** [comment]
Yes, use `mitmproxy` or some other proxy service to intercept and proxy the https traffic.

**Comment by MattTW** [comment]
> @MattTW  is the URL https://rest-prod.immedia-semi.com your own URL or blink's servers? I'm assuming you listened on a device when it was making calls to make the list of all requests going to Blink's servers?

It is Blink's, not mine, but depending on where you are in the world, the subdomain may be different.  

If you are a Mac person, try https://proxyman.io to watch the traffic, proxy your mobile phone to it. it is a very nicely done tool.
