### ISSUE TITLE
Auth token expiration time?

### ISSUE THREAD

**Issue by djboulia** [MattTW/BlinkMonitorProtocol#48]
I'm using node-blink-security on the back end of a web app and noticed that the the auth token seems to be expiring after 24 hours.  I've made a change to my code to refresh the module every few hours to work around this, but was wondering if there's a defined expiration for the auth token received at login.

**Comment by colinbendell** [comment]
it's not clear. best to just catch the 401 response and re-auth when you get the 401

**Comment by eliveikis** [comment]
Hi - we ran into this as it appears our tokens are timing out. Is there any known way to obtain a new token without using username and password? Thank you!
