### ISSUE TITLE
State of the API

### ISSUE THREAD

**Issue by JpEncausse** [MattTW/BlinkMonitorProtocol#5]
Hi,
Does the API still working ?

- I correctly get an AUTH TOKEN from a POST to /login
- I also get the networks ID list

But when I try to access /networks or /homescreen in GET I get { "message": "Unauthorized Access" }

**Comment by Zipsnet** [comment]
@JpEncausse https://community.smartthings.com/t/release-official-blink-camera-device-handler-with-motion-sensor-live-video-streaming-integration-with-smartthings-shm-temperature-signals-and-push-notifications/40535

**Comment by FranMontero** [comment]
@JpEncausse I had the same problem and figured it out. You are probably from Europe or other non-US region (as me). Look at the "region" part of the /login response. You should use this as the subdomain in subsequent calls, in my case is "**prde**.immedia-semi.com" instead of "**prod**.immedia-semi.com"

**Comment by JpEncausse** [comment]
Yes, I look à HTTPS stream an see it was an other URL, and it works !
I also made a Node-RED component.

BTW
- is there a command to trigger a snapshot ? 
- how do you pull events ? Every minutes ?

**Comment by MattTW** [comment]
Sorry for the delay on this. 

Didn't realize there were potentially different URL's for different regions.   Will look at updating the doc, thanks.

There is extra doc just pulled in that has more commands like snapshots.

**Comment by asksven** [comment]
@MattTW I just submitted a PR that covers the way to determine the REST endpoint URLs based on the region

**Comment by MattTW** [comment]
Excellent, thanks @asksven!
