### ISSUE TITLE
Owls vs Cameras

### ISSUE THREAD

**Issue by tomhobsonxd** [MattTW/BlinkMonitorProtocol#61]
Hi,

When pulling the list of cameras using the homescreen POST, I am given an empty array of cameras but one entry in the "owls" object.

After a bit of reading, this is because the camera I have is a Blink Mini.
When I call liveview with my owls id, I am given a 500 error. How do I call liveview for these owl objects? I want the RTSPS address to open a stream eventually

Thanks!

**Comment by jdinardo30** [comment]
Figured this out after looking at [camera.py](https://github.com/fronzbot/blinkpy/blob/dev/blinkpy/camera.py) in the blinkpy library.  Here's the differences:

Camera: /api/v5/accounts/{AccountID}/networks/{NetworkID}/cameras/{CameraID}/liveview

Owl: /api/**v1**/accounts/{AccountID}/networks/{NetworkID}/**owls**/**{OwlID}**/liveview

**Comment by tomhobsonxd** [comment]
Thanks for that! I'll check it out
